version: "3.8"
services:
  sync-pyth:
    build: .
    # Env file containing the minio credentials
    env_file:
      - .env
    # environment:
    #   - MINIO_ENDPOINT=minio:9000
    #   - BUCKET_NAME=test
    #   - CREATE_BUCKET=True
    depends_on:
      - minio
    networks:
      - s3_network
    entrypoint: ["poetry", "run", "python", "-m", "s3_synchroniser.main"]
    command:
      - "--endpoint_url"
      - "http://minio:9000"
      - "--bucket_name"
      - "test"
      - "--local_path"
      - "/app/data_to_sync"
      - "--create_bucket"
      - "True"
      - "--aws-region"
      - "us-east-1"
    volumes:
      - ./data_to_sync:/app/data_to_sync

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - s3_network

networks:
  s3_network:
    driver: bridge
